# Generated by Django 3.1.3 on 2021-01-15 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math_text', models.CharField(max_length=200)),
                ('hash_text', models.CharField(max_length=200)),
                ('file_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkradzioneWzoryWeb.file')),
            ],
        ),
    ]
