# Generated by Django 3.1.3 on 2021-01-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkradzioneWzoryWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
    ]
