# Generated by Django 3.1.3 on 2020-12-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkradzioneWzoryWeb', '0002_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
