# Generated by Django 3.1.3 on 2020-12-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkradzioneWzoryWeb', '0003_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
