# Generated by Django 3.1.3 on 2020-12-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SkradzioneWzoryWeb', '0004_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('equations', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
